# elasticsearch-master.deployment.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitoring
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  serviceName: elasticsearch-master
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      affinity:
        # Try to put each ES master node on a different node in the K8s cluster
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - elasticsearch
                    - key: role
                      operator: In
                      values:
                        - master
                topologyKey: kubernetes.io/hostname
      # spec.template.spec.initContainers
      initContainers:
        # Fix the permissions on the volume.
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: fix-the-volume-permission
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-master-storage
              mountPath: /usr/share/elasticsearch/data
        # Increase the default vm.max_map_count to 262144
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
        - name: increase-the-vm-max-map-count
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
        # Increase the ulimit
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: increase-the-ulimit
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true

      # spec.template.spec.containers
      containers:
        - name: elasticsearch-master
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          ports:
            - containerPort: 9300
              name: transport
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "0.25"
            limits:
              cpu: 1
              memory: 1Gi

          # spec.template.spec.containers[elasticsearch].env
          env:
            - name: NODE_LIST
              value: "elasticsearch-master.monitoring.svc.cluster.local"
            - name: MASTER_NODES
              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m

            - name: CLUSTER_NAME
              value: elasticsearch
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          # spec.template.spec.containers[elasticsearch].volumeMounts
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
            - name: elasticsearch-master-storage
              mountPath: /usr/share/elasticsearch/data

      # spec.template.spec
      volumes:
        - name: config
          configMap:
            name: elasticsearch-master-config
        - name: "elasticsearch-master-storage"
          emptyDir:
            medium: ""
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: monitoring
  name: elasticsearch-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master

#---
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  namespace: monitoring
#  name: elasticsearch-master
#  labels:
#    app: elasticsearch
#    role: master
#spec:
#  serviceName: elasticsearch-master
#  replicas: 3
#  selector:
#    matchLabels:
#      app: elasticsearch
#      role: master
#  template:
#    metadata:
#      labels:
#        app: elasticsearch
#        role: master
#    spec:
#      affinity:
#        # Try to put each ES master node on a different node in the K8s cluster
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 100
#              podAffinityTerm:
#                labelSelector:
#                  matchExpressions:
#                    - key: app
#                      operator: In
#                      values:
#                        - elasticsearch
#                    - key: role
#                      operator: In
#                      values:
#                        - master
#                topologyKey: kubernetes.io/hostname
#      # spec.template.spec.initContainers
#      initContainers:
#        # Fix the permissions on the volume.
#        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
#        - name: fix-the-volume-permission
#          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
#          securityContext:
#            privileged: true
#          volumeMounts:
#            - name: elasticsearch-master-persistent-storage
#              mountPath: /usr/share/elasticsearch/data
#        # Increase the default vm.max_map_count to 262144
#        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
#        - name: increase-the-vm-max-map-count
#          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#          command: ['sysctl', '-w', 'vm.max_map_count=262144']
#          securityContext:
#            privileged: true
#        # Increase the ulimit
#        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
#        - name: increase-the-ulimit
#          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#          command: ['sh', '-c', 'ulimit -n 65536']
#          securityContext:
#            privileged: true
#
#      # spec.template.spec.containers
#      containers:
#        - name: elasticsearch-master
#          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#          ports:
#            - containerPort: 9300
#              name: transport
#          livenessProbe:
#            tcpSocket:
#              port: transport
#            initialDelaySeconds: 20
#            periodSeconds: 10
#          resources:
#            requests:
#              cpu: "0.25"
#            limits:
#              cpu: 1
#              memory: 1Gi
#
#          # spec.template.spec.containers[elasticsearch].env
#          env:
#            - name: NODE_LIST
#              value: "elasticsearch-master.monitoring.svc.cluster.local"
#            - name: MASTER_NODES
#              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
#            - name: ES_JAVA_OPTS
#              value: -Xms512m -Xmx512m
#
#            - name: CLUSTER_NAME
#              value: elasticsearch
#            - name: NODE_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#
#          # spec.template.spec.containers[elasticsearch].volumeMounts
#          volumeMounts:
#            - name: config
#              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
#              readOnly: true
#              subPath: elasticsearch.yml
#            - name: elasticsearch-master-persistent-storage
#              mountPath: /usr/share/elasticsearch/data
#      volumes:
#        - name: config
#          configMap:
#            name: elasticsearch-master-config
#
#  # spec.volumeClaimTemplates
#  volumeClaimTemplates:
#    - metadata:
#        name: elasticsearch-master-persistent-storage
#        annotations:
#          volume.beta.kubernetes.io/storage-class: "standard"
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: standard
#        resources:
#          requests:
#            storage: 10Gi
#---
#apiVersion: policy/v1beta1
#kind: PodDisruptionBudget
#metadata:
#  namespace: monitoring
#  name: elasticsearch-master
#spec:
#  maxUnavailable: 1
#  selector:
#    matchLabels:
#      app: elasticsearch
#      role: master