# kibana.alert.service.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana
  labels:
    app: kibana
    role: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    name: webinterface
  selector:
    app: kibana
    role: kibana
---