# kibana-alert.od.service.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana-alert
  labels:
    app: kibana-alert
    role: kibana-alert
spec:
  type: LoadBalancer
  ports:
  - port: 5602
    name: webinterface
  selector:
    app: kibana-alert
    role: kibana-alert
---