#kibana.alert.deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: kibana-alert
  labels:
    app: kibana-alert
    role: kibana-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-alert
      role: kibana-alert
  template:
    metadata:
      labels:
        app: kibana-alert
        role: kibana-alert
    spec:
      containers:
      - name: kibana-alert
        image: "${ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/monitoring:kbn.dteixeira-v7.5.2"
        ports:
        - containerPort: 5602
          name: webinterface
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-client.monitoring.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USER
          value: "kibana"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-kibana
              key: password
        - name: ELASTALERT_HOST
          value: "elastalert.monitoring.svc.cluster.local"
        - name: ELASTALERT_PORT
          value: "3030"
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-alert-config
---