# metric-aws.configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: metricbeat-aws-billing-config
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-

    # Configure modules
    metricbeat.modules:
      - module: aws
        period: 300s
        metricsets:
          - cloudwatch
        access_key_id: '${AWS_ACCESS_KEY_ID:""}'
        secret_access_key: '${AWS_SECRET_ACCESS_KEY:""}'
        regions: ["us-east-1"]
        metrics:
          - namespace: AWS/Billing
        dimensions:
          - currency: USD


    # Connection to ElasticSearch
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

    # Connection to Kibana to import pre-existing dashboards
    setup.kibana:
      host: '${KIBANA_HOST:kibana}:${KIBANA_PORT:5601}'

    # Import pre-existing dashboards
    setup.dashboards.enabled: true
---
