apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  namespace: monitoring
  labels:
    app: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      serviceAccountName: elastalert
      containers:
        - name: elastalert
          image: "${ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/monitoring:dteixeira-elastalert-v7.0.2"
          ports:
            - name: web
              containerPort: 3030
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-client.monitoring.svc.cluster.local"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: SMTP_USERNAME
              value: "AKIAUGEOGUCH6NWBU6O3"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-smtp-credentials
                  key: password
          volumeMounts:
            - name: config
              mountPath: /opt/elastalert
            - name: rules
              mountPath: /opt/rules
      volumes:
        - name: rules
          configMap:
            name: logstash-rule
        - name: config
          configMap:
            name: elast-config